### ISSUE TITLE
🚀 [FEATURE]: Reshape .restqa.yml format

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#184]
### 👀 Background

RestQA is moving toward the test driven happiness concept.
We are trying to  move out of the focus on Integration test.

### ✌️ What is the actual behavior?

The current `.restqa.yml` file format is focus on integration test only.

### 🕵️‍♀️ How to reproduce the current behavior?

1. run the command `restqa init`
2. Look at the created file `.restqa.yml`

### 🤞 What is the expected behavior?

Have a more explicit `.restqa.yml` that matching the overall scope of restqa:
- Unit test
- Performance test
- Api specification
- API collection
- CI / CD

### 😎 Proposed solution.

New format proposed:

```yml
version: 0.0.1
metadata:
  code: ACCOUNT
  name: Account
  description: Microservice managing Accounts
tests:
  unit:
    port: 8080
    command: npm run dev
    data:
      channel: 'csv'
      config:
        folder: 'test/data'
        delimiter: ','
  integration:
    - name: testing
      default: true
      url: http://localhost:8000
      data:
        channel: 'csv'
        config:
          folder: 'test/data'
          delimiter: ','
      outputs:
        - type: html
          enabled: true
        - type: file
          enabled: true
          config:
            path: restqa-result.json
  performance:
    tool: artillery
    outputFolder: "tests/performance"
    onlySuccess: true

specification:
  title: "override title"
  description: "Overrid description"
  matchs:
    ids:
    - /^(\d+)\@/
    - /^(\d+)/
    - /^[a-zA-Z0-9]+\=$/
  export: "./openapi.yml"

collection:
  tool: "postman"
  export: "./postman-collection.yml"

plugins:
  - name: "@restqa/restqapi"
  - name: "@restqa/http-mock-plugin"
    config:
      folder: ./tests/mocks
      envs:
        GITHUB_API: github
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
