### ISSUE TITLE
🚀 [FEATURE]:  Gamify current Test Status

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#220]
### 👀 Background

As an engineer we need to access to the test result page a lot...
Most of the time we have a challenge to engage with the current way of the information are showed on the screen

### ✌️ What is the actual behavior?

Currently the test result showed are shared through a Pie chart.
Pie chart:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/4768226/200103329-07a64984-bdad-4a2e-b7b8-eff177db0e0d.png">

Homepage:

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/4768226/200103436-68a912ce-d725-46ac-96d6-97511909fe6c.png">

### 🕵️‍♀️ How to reproduce the current behavior?

1. install restqa
2. run the command `npm i`
3. go to the folder *example*
4. run the command `npm run happy`
5. You should see a sample test result

### 🤞 What is the expected behavior?

While we open the test result we would like to see:

* If test result are successful: An happy face
* If test result are partially successful: An sad face
* If test result are failing: An sick face

### 😎 Proposed solution.

We should defined 3 status level:
* Successful
* acceptable
* Failed

Then the  developer should have a way to configure the thresholds of the test result.
Example:

* successful  = 100%
* Acceptable = 90%
* (then naturally everything under 90% is considered as failed)

Proposal:
On the `.restqa.yml` in the `tests.local` settings section we could add:

```
#.restqa.yml
---
version: 0.0.1
metadata:
  code: EXAMPLE-RESTQA
  name: Example Restqa
  description: Delicious Microservice example maintained with RestQA
tests:
  local:
    port: 8887
    command: npm run dev
    tresholds:
      success: 100. #default 100
      accepted: 90 #default 100
```

⚠️ Required before starting:

- [ ] Icon to represent the status
- [ ] Position of the status icon on the report page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
