### ISSUE TITLE
🚀 [FEATURE]: Inject environment variable to microservice

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#351]
### 👀 Background

In order to pass a context to a microservice environement variable becomes very handy

### ✌️ What is the actual behavior?

There is way to pass directly an environement variable to a microservice through configuration.
Only using : `ENV=test npm test`

### 🕵️‍♀️ How to reproduce the current behavior?

N/A

### 🤞 What is the expected behavior?

We should be able to pass en environment variable through the restqa config file

### 😎 Proposed solution.

have the following in the `.restqa.yml` file

```
version: 0.0.1
metadata:
  code: -NEXT-BEST-OFFER-API
  name: "@next-best-offer/api"
  description: Delicious Microservice maintained with RestQA
tests:
  local:
    port: "3000"
    command: npm start
   envs: 
     FOO: bar
  performance:
    tool: artillery
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
