### ISSUE TITLE
🚀 [FEATURE][Plugin Proposal]: JWT plugin 

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#363]
### 👀 Background

Nowadays in order to be stateless microservices are using JWT to be secured

### ✌️ What is the actual behavior?

Currently in order to use RestQA to  test a microservice secured by a JWT. The user will have 2 options:

1. Create a custom step definition to sign the JWT using a private key
2. Create a custom step definition to retireve a JWT from a thrid party

### 🕵️‍♀️ How to reproduce the current behavior?

Follow the instruction here https://dashboard.restqa.io/#/documentation/given-authorization

### 🤞 What is the expected behavior?

We should be able to create JWT for test purpose just using a command or 2 out of the box

### 😎 Proposed solution.

Having a plugin that can be configure like:

`npm i -D @restqa/plugin-jwt`

Then configure it in the `.restqa.yml`

```yaml
plugins:
  - name: '@restqa/plugin-jwt
    config:
      issuer: 'https://iam.restqa.io'
     claims:
       foo: bar
     algorithm: RS256
     privateKey: ./data/private-key.test.pem
```

Then we can use the following step definition:

To get a default JWT

```gherkin
Given a JWT
```

A JWT sign with specific claim
```gherkin
Given a JWT:
"""
{
  "foo": "bar"
}
"""
```

An expired JWT:
```gherkin
Given a JWT expired X minutes ago
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
