### ISSUE TITLE
Ignoring the report files generated by restqa

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#41]
Hello 👋,

### 👀 Background 

Currently, after the RestQA initialization (command: `restqa init`), the user use the default configuration that includes the html reporter and the json file reporter.

Example:

```
version: 0.0.1
metadata:
  code: JSON-PLACEHOLDER
  name: jsonplaceholder from typecode
  description: An example application to demo RestQA Features
environments:
  - name: local
    default: true
    plugins:
      - name: "@restqa/restqapi"
        config:
          url: https://jsonplaceholder.typicode.com
    outputs:
      - type: html
        enabled: true
      - type: file
        enabled: true
        config:
          path: restqa-result.json
```

It mean RestQA will generate 2 kind of report: html + json

### ✌️ What is the actual behavior? 

When the user is using RestQA for the first time,  2 file related to the report will be generated:
1. the folder `report`
2. the file `restqa-result.json`

However those files are just reporting information. **They should be ignore from the version control tool (GIT)**

### 🕵️‍♀️ How to reproduce the current behavior? 

1. Install RestQA
2. Run the command `restqa init` to initialize a brand new project
3. Run the command `restqa run` to create the first report
4. Run the command `git status`

You will see the `report ` folder and the file `restqa-result.json` appear on the list of the git status.

###   🤞 What is the expected behavior?

When the user will would like to commit his changes to the version control, the files `report` and `restqa-result.json` should be ignored.

###   😎 Proposed solution.

During the initialization of restqa thought the command `restqa init` we should check if the file `./.gitignore` already exists or create it if it doesn't exists.

Then add the following lines into it.
```
./report
./restqa-result.json
``` 

Cheers.
