### ISSUE TITLE
override default api timeout

### ISSUE THREAD

**Issue by salismt** [restqa/restqa#78]
**Context**

I have a case where the API is longer than the default timeout (5000 ms)
I would like to be able to override timeout config in `restqapi`

**Proposal**

```
plugins:
      - name: "@restqa/restqapi"
        config: 
          url: https://api.restqa.io
          timeout: 30000
```

**Alternatives**

**Has the Step been requested before?**

Not yet

**If the Step request is approved, would you be willing to submit a PR?**

Yes
